// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9dRfmK27NUFSQblXk7-uPWjJJTcTSEA',
    appId: '1:870959139579:web:532731a01bb3955ced7e5e',
    messagingSenderId: '870959139579',
    projectId: 'flutter-test-8179b',
    authDomain: 'flutter-test-8179b.firebaseapp.com',
    storageBucket: 'flutter-test-8179b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkeTolrkbZaFZDdS6psghVlQHpnKFXPqU',
    appId: '1:870959139579:android:11489ee38414d864ed7e5e',
    messagingSenderId: '870959139579',
    projectId: 'flutter-test-8179b',
    storageBucket: 'flutter-test-8179b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACskWWIeCSbruFXQDQK59oYpdxtr0fIvs',
    appId: '1:870959139579:ios:5a330d43fa351df1ed7e5e',
    messagingSenderId: '870959139579',
    projectId: 'flutter-test-8179b',
    storageBucket: 'flutter-test-8179b.appspot.com',
    iosClientId: '870959139579-npat5le3fnu9thlsqin6qeoe374vssa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACskWWIeCSbruFXQDQK59oYpdxtr0fIvs',
    appId: '1:870959139579:ios:0eef8f7da5566325ed7e5e',
    messagingSenderId: '870959139579',
    projectId: 'flutter-test-8179b',
    storageBucket: 'flutter-test-8179b.appspot.com',
    iosClientId: '870959139579-eugrb98f8efbhtroe0po15r43idfkklq.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto.RunnerTests',
  );
}
